In [1]:
def generate_regular_problems(num_vertices=10, degree=3):
    graph = connect_graph(nx.erdos_renyi_graph(num_vertices, edge_prob))
    graph_edges = defaultdict(set)
    num_edges = 0
    nx_graph = graph
    for v1, v2 in graph.edges:
        graph_edges[v1].add(v2)
        graph_edges[v2].add(v1)
        num_edges += 1
    return 

In [2]:
import networkx as nx
import torch
import copy
import numpy as np
import random

In [4]:
graph1 = nx.erdos_renyi_graph(10, 0.3)

In [6]:
graph1.node

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9))

In [42]:
len(graph1)

10

In [13]:
type(torch.tensor(random.choice(list(graph1.nodes))))

torch.Tensor

In [ ]:
copy.deepcopy(graph1)

In [27]:
graph2 = nx.erdos_renyi_graph(10, 0.3)

In [51]:
torch.FloatTensor(list(graph1.node))[:, None]

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
l = [graph1, graph2]

In [ ]:
l

In [ ]:
t = torch.FloatTensor([list(graph.node) for graph in l])

In [21]:
t= torch.FloatTensor(list(graph1.node))

In [28]:
k= torch.FloatTensor(list(graph2.node))

In [38]:
q = torch.stack([t,k])

In [39]:
q.size()

torch.Size([2, 10])

In [ ]:
torch.zeros(32, 1, 5)

In [ ]:
copy.deepcopy(l)

In [ ]:
torch.zeros(1)

In [ ]:
f = torch.tensor([[list(g.neighbors(i)) for i in list(g.nodes)] for g in l])

In [15]:
valids = np.ones((10, 10))

In [16]:
valids

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
for j in list(graph1.nodes):
    for k in list(graph1.neighbors(j)):
        valids[j,k] = 0

In [18]:
valids = torch.tensor(valids, dtype=torch.uint8)

In [19]:
valids

tensor([[1, 1, 1, 0, 0, 0, 1, 0, 1, 1],
        [1, 1, 0, 0, 0, 1, 1, 1, 0, 1],
        [1, 0, 1, 1, 1, 1, 0, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 1, 0, 1, 1],
        [0, 0, 1, 0, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 0, 1, 1, 0, 0, 1, 1],
        [1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
        [0, 1, 1, 0, 1, 0, 1, 1, 1, 1],
        [1, 0, 1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 1]], dtype=torch.uint8)

In [ ]:
l[0].edges

In [ ]:
torch.tensor(graphs)

In [ ]:
list(graph.nodes)

In [ ]:
f

In [ ]:
f.unsqueeze(1)

In [ ]:
target = torch.ones(2, 10, 10, dtype=torch.uint8)

In [ ]:
target

In [ ]:
target.index_fill(index=graphs, value=0, dim=3)

In [ ]:
torch.zeros(2, 1, 10,dtype=torch.uint8)

In [ ]:
valids.index_select(dim=2, index=o.unsqueeze(-1))

In [ ]:
o = torch.tensor([3, 4])

In [ ]:
o.view(-1)

In [ ]:
valids.gather(2, o.unsqueeze(-1))

In [ ]:
valids[:, 3, :]

In [ ]:
valids

In [ ]:
o = torch.tensor([3, 4])

In [ ]:
h = torch.cat([torch.index_select(a, 0, i) for a, i in zip(valids, o)])[:, None]

In [ ]:
h.size()

In [ ]:
m = torch.randn(4,2)

In [ ]:
m

In [ ]:
ids = torch.Tensor([1,1,0,0]).long()

In [ ]:
ids

In [ ]:
print(m.gather(1, ids.view(-1,1)))

In [ ]:
o.view(-1,1)

In [ ]:
valids.gather(1, o.view(-1,1))

In [ ]:
A = torch.FloatTensor([[[1, 2, 3], [1, 2, 5]], [[4, 5, 6], [4, 5, 7]], [[7, 8, 9], [7,10, 9]]])

In [ ]:
A

In [ ]:
ind = torch.LongTensor([1, 0, 1])

In [ ]:
ind

In [ ]:
torch.cat([torch.index_select(a, 0, i) for a, i in zip(A, ind)]).unsqueeze(0)

In [ ]:
import math

In [ ]:
torch.tensor(-math.inf)

In [ ]:
torch.functional.F.log_softmax(torch.tensor(-math.inf), dim=0)

In [ ]:
torch.zeros(32, 1, 10, dtype=torch.uint8)

In [ ]:
torch.zeros(32,1).view(-1)

In [ ]:
torch.zeros(1, dtype=torch.int64)