In [3]:
def generate_regular_problems(num_vertices=10, degree=3):
    graph = connect_graph(nx.erdos_renyi_graph(num_vertices, edge_prob))
    graph_edges = defaultdict(set)
    num_edges = 0
    nx_graph = graph
    for v1, v2 in graph.edges:
        graph_edges[v1].add(v2)
        graph_edges[v2].add(v1)
        num_edges += 1
    return 

In [91]:
import networkx as nx
import torch
import copy
import numpy as np
import random
import math

In [19]:
graph1 = nx.erdos_renyi_graph(10, 0.3)

In [125]:
graph1.edges

EdgeView([(0, 2), (0, 3), (0, 7), (1, 5), (4, 5), (4, 7), (5, 6), (5, 9), (6, 9)])

In [127]:
list(graph1.neighbors(2))

[0]

In [ ]:
graph1.node

In [ ]:
len(graph1)

In [ ]:
type(torch.tensor(random.choice(list(graph1.nodes))))

In [ ]:
copy.deepcopy(graph1)

In [20]:
graph2 = nx.erdos_renyi_graph(10, 0.3)

In [ ]:
torch.FloatTensor(list(graph1.node))[:, None]

In [21]:
l = [graph1, graph2]

In [ ]:
l

In [ ]:
t = torch.FloatTensor([list(graph.node) for graph in l])

In [ ]:
t= torch.FloatTensor(list(graph1.node))

In [ ]:
k= torch.FloatTensor(list(graph2.node))

In [ ]:
q = torch.stack([t,k])

In [ ]:
q.size()

In [ ]:
torch.zeros(32, 1, 5)

In [ ]:
copy.deepcopy(l)

In [ ]:
torch.zeros(1)

In [23]:
f = torch.tensor([[list(g.neighbors(i)) for i in list(g.nodes)] for g in l])

ValueError: expected sequence of length 3 at dim 2 (got 1)

In [15]:
valids = np.ones((10, 10))

In [27]:
(valids == 1).all()

True

In [17]:
for j in list(graph1.nodes):
    for k in list(graph1.neighbors(j)):
        valids[j,k] = 0

NameError: name 'graph1' is not defined

In [ ]:
valids = torch.tensor(valids, dtype=torch.uint8)

In [ ]:
valids

In [ ]:
l[0].edges

In [ ]:
torch.tensor(graphs)

In [ ]:
list(graph.nodes)

In [ ]:
f

In [ ]:
f.unsqueeze(1)

In [ ]:
target = torch.ones(2, 10, 10, dtype=torch.uint8)

In [ ]:
target

In [ ]:
target.index_fill(index=graphs, value=0, dim=3)

In [ ]:
torch.zeros(2, 1, 10,dtype=torch.uint8)

In [ ]:
valids.index_select(dim=2, index=o.unsqueeze(-1))

In [ ]:
o = torch.tensor([3, 4])

In [ ]:
o.view(-1)

In [ ]:
valids.gather(2, o.unsqueeze(-1))

In [ ]:
valids[:, 3, :]

In [ ]:
valids

In [5]:
o = torch.tensor([3, 4])

In [6]:
h = torch.cat([torch.index_select(a, 0, i) for a, i in zip(valids, o)])[:, None]

NameError: name 'valids' is not defined

In [ ]:
h.size()

In [ ]:
m = torch.randn(4,2)

In [ ]:
m

In [ ]:
ids = torch.Tensor([1,1,0,0]).long()

In [ ]:
ids

In [ ]:
print(m.gather(1, ids.view(-1,1)))

In [7]:
o.view(-1,1)

tensor([[3],
        [4]])

In [ ]:
valids.gather(1, o.view(-1,1))

In [132]:
A = torch.FloatTensor([[[1, 2, 3], [1, 2, 5]], [[4, 5, 6], [4, 5, 7]], [[7, 8, 9], [7,10, 9]]])

In [133]:
A

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  5.]],

        [[ 4.,  5.,  6.],
         [ 4.,  5.,  7.]],

        [[ 7.,  8.,  9.],
         [ 7., 10.,  9.]]])

In [186]:
ind = torch.LongTensor([[1], [0], [1]])

In [216]:
ind[:, None]

tensor([[[1]],

        [[0]],

        [[1]]])

In [170]:
z = torch.cat([torch.index_select(a, 0, i) for a, i in zip(A, ind)])[:, None]

In [182]:
z

tensor([[[ 1.,  2.,  5.]],

        [[ 4.,  5.,  6.]],

        [[ 7., 10.,  9.]]])

In [183]:
k = (torch.tensor([0]), torch.tensor([1]), torch.tensor([2]))

In [217]:
mask = torch.zeros(3, 1, 3)
mask.scatter_(2, ind[:, None], 1.)

tensor([[[0., 1., 0.]],

        [[1., 0., 0.]],

        [[0., 1., 0.]]])

In [215]:
mask

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]])

In [211]:
z.masked_fill()

TypeError: masked_fill() missing 2 required positional arguments: 'mask' and 'value'

In [ ]:
import math

In [ ]:
torch.tensor(-math.inf)

In [ ]:
torch.functional.F.log_softmax(torch.tensor(-math.inf), dim=0)

In [41]:
y = torch.zeros(32, 1, 10, dtype=torch.uint8)

In [ ]:
torch.zeros(32,1).view(-1)

In [ ]:
torch.zeros(1, dtype=torch.int64)

In [29]:
x = torch.tensor([[[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0]],

        [[1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1]],

        [[1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1]],

        [[1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0]],

        [[0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0]],

        [[1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0]],

        [[1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1]],

        [[1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1]]],
       dtype=torch.uint8)

In [74]:
(x == 1)

tensor(96)

In [60]:
(y.sum() == 0)

tensor(1, dtype=torch.uint8)

In [66]:
y.view(-1).sum() == 0

tensor(1, dtype=torch.uint8)

In [62]:
y.all()

tensor(0, dtype=torch.uint8)

In [63]:
x.all()

tensor(0, dtype=torch.uint8)

In [130]:
y

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0

In [131]:
(y == 0).sum() == 0

tensor(0, dtype=torch.uint8)

In [85]:
torch.is_nonzero(x.view(-1))

RuntimeError: bool value of Tensor with more than one value is ambiguous

In [129]:
x

tensor([-0.5994,    -inf, -0.7967])

In [110]:
x = torch.nn.functional.log_softmax(torch.tensor([-0.1578, -math.inf, -0.3551]))

/anaconda3/envs/graph/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  """Entry point for launching an IPython kernel.


In [118]:
x.multinomial(1)

RuntimeError: invalid argument 2: invalid multinomial distribution (encountering probability entry < 0) at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.6/conda/conda-bld/pytorch_1544137972173/work/aten/src/TH/generic/THTensorRandom.cpp:298

In [116]:
x

tensor([-0.5994,    -inf, -0.7967])