In [ ]:
def generate_regular_problems(num_vertices=10, degree=3):
    graph = connect_graph(nx.erdos_renyi_graph(num_vertices, edge_prob))
    graph_edges = defaultdict(set)
    num_edges = 0
    nx_graph = graph
    for v1, v2 in graph.edges:
        graph_edges[v1].add(v2)
        graph_edges[v2].add(v1)
        num_edges += 1
    return 

In [144]:
import networkx as nx
import torch
import copy
import numpy as np

In [13]:
graph1 = nx.erdos_renyi_graph(10, 0.3)

In [29]:
copy.deepcopy(graph1)

In [14]:
graph2 = nx.erdos_renyi_graph(10, 0.3)

In [15]:
torch.FloatTensor(list(graph.node))

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
l = [graph1, graph2]

In [24]:
t = torch.FloatTensor([list(graph.node) for graph in l]).unsqueeze(-1)

In [25]:
t.size()

torch.Size([2, 10, 1])

In [26]:
t

tensor([[[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]],

        [[0.],
         [1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]])

In [32]:
torch.zeros(32, 1, 5)

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[

In [30]:
copy.deepcopy(l)

In [31]:
torch.zeros(1)

tensor([0.])

In [136]:
f = torch.tensor([[list(g.neighbors(i)) for i in list(g.nodes)] for g in l])

ValueError: expected sequence of length 1 at dim 2 (got 3)

In [155]:
valids = np.ones((2, 10, 10))

In [156]:
valids

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]

In [157]:
for i, g in enumerate(l):
    for j in list(g.nodes):
        for k in list(g.neighbors(j)):
            valids[i,j,k] = 0

In [162]:
valids = torch.tensor(valids, dtype=torch.uint8)

In [154]:
l[0].edges

EdgeView([(0, 6), (1, 3), (1, 6), (1, 9), (2, 3), (3, 9), (4, 8), (5, 7), (6, 7), (8, 9)])

In [142]:
torch.tensor(graphs)

ValueError: expected sequence of length 1 at dim 2 (got 3)

In [128]:
list(graph.nodes)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
f

tensor([[1, 2, 9],
        [1, 2, 8]])

In [117]:
f.unsqueeze(1)

tensor([[[1, 2, 9]],

        [[1, 2, 8]]])

In [106]:
target = torch.ones(2, 10, 10, dtype=torch.uint8)

In [107]:
target

tensor([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]], dtype=torch.uint8)

In [140]:
target.index_fill(index=graphs, value=0, dim=3)

TypeError: index_fill_() received an invalid combination of arguments - got (int, list, int), but expected one of:
 * (int dim, Tensor index, Tensor value)
      didn't match because some of the arguments have invalid types: (int, list, int)
 * (int dim, Tensor index, Number value)
      didn't match because some of the arguments have invalid types: (int, list, int)


In [161]:
torch.zeros(2, 1, 10,dtype=torch.uint8)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=torch.uint8)

In [525]:
valids.index_select(dim=2, index=o.unsqueeze(-1))

RuntimeError: invalid argument 3: Index is supposed to be 1-dimensional at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.6/conda/conda-bld/pytorch_1544137972173/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:164

In [572]:
o = torch.tensor([3, 4])

In [571]:
o.view(-1)

tensor([3, 4])

In [477]:
valids.gather(2, o.unsqueeze(-1))

RuntimeError: Expected tensor [2, 1, 1], src [2, 10, 10] and index [2, 1, 1] to have the same size apart from dimension 2

In [582]:
valids[:, 3, :]

tensor([[1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
        [1, 0, 0, 1, 1, 1, 1, 1, 0, 1]], dtype=torch.uint8)

In [570]:
valids

tensor([[[1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
         [1, 1, 1, 0, 1, 1, 0, 1, 1, 0],
         [1, 1, 1, 0, 1, 1, 1, 1, 1, 1],
         [1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 0, 1],
         [1, 1, 1, 1, 1, 1, 1, 0, 1, 1],
         [0, 0, 1, 1, 1, 1, 1, 0, 1, 1],
         [1, 1, 1, 1, 1, 0, 0, 1, 1, 1],
         [1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
         [1, 0, 1, 0, 1, 1, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
         [1, 1, 1, 0, 1, 1, 0, 0, 1, 0],
         [1, 1, 1, 0, 0, 1, 1, 1, 0, 0],
         [1, 0, 0, 1, 1, 1, 1, 1, 0, 1],
         [1, 1, 0, 1, 1, 0, 1, 1, 1, 1],
         [1, 1, 1, 1, 0, 1, 1, 0, 0, 1],
         [0, 0, 1, 1, 1, 1, 1, 1, 0, 1],
         [1, 0, 1, 1, 1, 0, 1, 1, 1, 0],
         [1, 1, 0, 0, 1, 0, 0, 1, 1, 1],
         [1, 0, 0, 1, 1, 1, 1, 0, 1, 1]]], dtype=torch.uint8)

In [719]:
o = torch.tensor([3, 4])

In [752]:
h = torch.cat([torch.index_select(a, 0, i) for a, i in zip(valids, o)])[:, None]

In [759]:
h.size()

torch.Size([2, 1, 10])

In [583]:
m = torch.randn(4,2)

In [584]:
m

tensor([[-0.3828, -0.1979],
        [ 0.9034, -0.0449],
        [-1.1909, -0.5410],
        [-1.1957,  0.2495]])

In [585]:
ids = torch.Tensor([1,1,0,0]).long()

In [586]:
ids

tensor([1, 1, 0, 0])

In [587]:
print(m.gather(1, ids.view(-1,1)))

tensor([[-0.1979],
        [-0.0449],
        [-1.1909],
        [-1.1957]])


In [603]:
o.view(-1,1)

tensor([[3],
        [4]])

In [609]:
valids.gather(1, o.view(-1,1))

RuntimeError: invalid argument 4: Index tensor must have same dimensions as input tensor at /Users/administrator/nightlies/pytorch-1.0.0/wheel_build_dirs/conda_3.6/conda/conda-bld/pytorch_1544137972173/work/aten/src/TH/generic/THTensorEvenMoreMath.cpp:438

In [661]:
A = torch.FloatTensor([[[1, 2, 3], [1, 2, 5]], [[4, 5, 6], [4, 5, 7]], [[7, 8, 9], [7,10, 9]]])

In [662]:
A

tensor([[[ 1.,  2.,  3.],
         [ 1.,  2.,  5.]],

        [[ 4.,  5.,  6.],
         [ 4.,  5.,  7.]],

        [[ 7.,  8.,  9.],
         [ 7., 10.,  9.]]])

In [672]:
ind = torch.LongTensor([1, 0, 1])

In [673]:
ind

tensor([1, 0, 1])

In [685]:
torch.cat([torch.index_select(a, 0, i) for a, i in zip(A, ind)]).unsqueeze(0)

tensor([[[ 1.,  2.,  5.],
         [ 4.,  5.,  6.],
         [ 7., 10.,  9.]]])

In [616]:
import math

In [622]:
torch.tensor(-math.inf)

tensor(-inf)

In [623]:
torch.functional.F.log_softmax(torch.tensor(-math.inf), dim=0)

tensor(nan)

In [678]:
torch.zeros(32, 1, 10, dtype=torch.uint8)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0

In [758]:
torch.zeros(32,1).view(-1)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.])

In [641]:
torch.zeros(1, dtype=torch.int64)

tensor([0])